services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ErdiSyla
      POSTGRES_PASSWORD: lightweightNoReaction123
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5500:5432"
    networks:
      - schdlr_postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: erdisyla6@gmail.com
      PGADMIN_DEFAULT_PASSWORD: lessIsSometimesMore456
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - schdlr_postgres
    restart: unless-stopped

  schdlr-app:
    container_name: schdlr-app
    build: .
    ports:
      - "8080:8080"
    networks:
      - schdlr_postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/schdlr
    restart: unless-stopped

networks:
  schdlr_postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: