server:
  port: 8080

spring:
  application:
    name: schdlr
  datasource:
    url: jdbc:postgresql://postgres:5432/schdlr
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        allow_update_outside_transaction: 'false'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
logging:
  level:
    org:
      springframework:
        security: DEBUG
