server:
  port: 8080

spring:
  application:
    name: schdlr
  datasource:
    url: jdbc:postgresql://postgres:5432/schdlr
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
        allow_update_outside_transaction: false
    hibernate:
      ddl-auto: update
    show-sql: true 

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            client-id: 961446176422-8u34p7c03g5ht3d946mab7f6g9b8d9kk.apps.googleusercontent.com
            client-secret: ${CLIENT_SECRET}
              
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    root: INFO
    com.schdlr : DEBUG       
    org.springframework.security: DEBUG
  file:
    name: logs/application.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"


